version: '3'

networks:
  web:
    external: true
  django-max:
    external: false

volumes:
  production_postgres_data: {}
  production_postgres_data_backups: {}
  production_traefik: {}
  production_django_media: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile

    image: portfolio_max_production_django
    volumes:
      - production_django_media:/app/portfolio_max/media
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start
    networks:
      - web
      - django-max
    labels:
      - traefik.http.routers.django-johanna.rule=Host(`max-zimmermann.online`)
      - traefik.http.routers.django-johanna.tls=true
      - traefik.http.routers.django-johanna.tls.certresolver=le-resolver
      - traefik.port=5000

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: portfolio_max_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres
    networks:
      - django-max
    labels:
      - traefik.enable=false

  redis:
    image: redis:6
    networks:
      - django-max
    labels:
      - traefik.enable=false

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: portfolio_max_local_nginx
    depends_on:
      - django
    volumes:
      - production_django_media:/usr/share/nginx/media:ro
    networks:
      - django-max
    labels:
      - traefik.enable=false
